"""
Rewrite abstract synthetic DAG questions into realistic NL scenarios via LLM.

Takes a JSON file generated by gen_dag.py and replaces each `question` field with a
realistic, domain-specific rewrite. Supports two input modes:
  • With durations: keeps durations and constraints verbatim, changes step names.
  • Structure only: LLM invents step names, adds reasonable durations, and provides
    the answer (shortest possible time).
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

from dotenv import load_dotenv
load_dotenv()

from src.experiments.utils import build_llm_client
from src.gen_data.utils import compute_gold_makespan, parse_node_durations, compute_metrics


# ── Prompt ────────────────────────────────────────────────────────────────────

SYSTEM_PROMPT = """
You are a creative writer who specializes in turning abstract asynchronous planning problems into concrete, realistic scenarios.

You will be given an abstract asynchronous planning problem that has:
- A task title
- Numbered steps (with NO names or durations)
- Ordering constraints between steps

Your job: fill in each step with a concrete activity name and a realistic duration in natural language, making the problem feel like a real everyday task.

STRICT RULES:
1. Keep the task title EXACTLY as given.
2. Keep the EXACT same number of steps.
3. Copy ALL ordering constraints VERBATIM — same step numbers, same wording.
4. Copy the final Question line VERBATIM.
5. For each step, add:
   - A concrete, activity-specific name that fits the task (e.g., "Preheat the oven", "Sift the flour")
   - A reasonable duration in parentheses (e.g., (30 seconds), (5 minutes), (2 hours), (3 days), (1 week), (2 months), (1 year))
6. The step names should form a coherent, realistic workflow for the given task.
7. Use diverse but plausible durations — not every step should take the same amount of time or use the same unit.
8. The ordering constraints should make logical sense with the step names you choose.
9. Output ONLY the rewritten problem. No commentary, no markdown fences, no extra text.

EXAMPLE INPUT:
To audition for the school play, here are the steps needed.
Step 1.
Step 2.
Step 3.
Step 4.
Step 5.

These ordering constraints need to be obeyed when executing above steps:
Step 1 must precede Step 2.
Step 2 must precede Step 3 and 4.
Step 3 must precede Step 5.
Step 4 must precede Step 5.

Question: Assume that you need to execute all the steps to complete the task and that infinite resources are available. What is the shortest possible time to audition for the school play?

EXAMPLE OUTPUT:
To audition for the school play, here are the steps needed.
Step 1. Sign up for auditions (15 minutes)
Step 2. Get script to practice (15 minutes)
Step 3. Practice reading lines with friends (4 hours)
Step 4. Practice reading lines before bed (3 hours)
Step 5. Show up to auditions (15 minutes)

These ordering constraints need to be obeyed when executing above steps:
Step 1 must precede Step 2.
Step 2 must precede Step 3 and 4.
Step 3 must precede Step 5.
Step 4 must precede Step 5.

Question: Assume that you need to execute all the steps to complete the task and that infinite resources are available. What is the shortest possible time to audition for the school play?
"""


USER_TEMPLATE = """\
Here is an abstract asynchronous planning problem:
{abstract_question}
"""
# Rewrite it as a realistic, everyday scenario with step names and durations in natural language.


def _build_messages(abstract_question: str) -> list[dict]:
    return [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": USER_TEMPLATE.format(abstract_question=abstract_question)},
    ]


# ── Validation ────────────────────────────────────────────────────────────────

def _validate_rewrite(
    original: str, rewrite: str, n_steps: int
) -> bool:
    """
    Sanity check: rewrite has the right number of step lines, preserves
    all constraint step-number pairs.
    """
    if not rewrite or not rewrite.strip():
        return False

    step_lines = re.findall(r"^Step \d+\.", rewrite, re.MULTILINE)
    if len(step_lines) != n_steps:
        return False

    orig_pairs = set(re.findall(r"Step (\d+) must precede Step (\d+)\.", original))
    rewrite_pairs = set(re.findall(r"Step (\d+) must precede Step (\d+)\.", rewrite))
    if orig_pairs != rewrite_pairs:
        return False

    # When original has no durations (structure-only), rewrite must add them
    orig_durations = re.findall(r"\([^)]+\)", original)
    for d in orig_durations:
        if d not in rewrite:
            return False
    if not orig_durations:
        # Structure-only: each step line in rewrite must have a duration
        steps_with_dur = re.findall(r"^Step \d+\. .+ \([^)]+\)", rewrite, re.MULTILINE)
        if len(steps_with_dur) != n_steps:
            return False

    return True


def _estimate_max_tokens(n_steps: int, n_constraints: int) -> int:
    """Estimate token budget."""
    base = n_steps * 35 + n_constraints * 15 + 200
    return max(8192, base)


# ── Main pipeline ─────────────────────────────────────────────────────────────

_MAX_REWRITE_RETRIES = 5


def rewrite_dataset(
    samples: list[dict],
    model_name: str,
    temperature: float,
    max_tokens: int,
    num_workers: int,
    max_retries: int = _MAX_REWRITE_RETRIES,
) -> list[dict]:
    import re as _re
    import concurrent.futures
    from tqdm import tqdm

    llm = build_llm_client(
        model_name=model_name,
        temperature=temperature,
        max_tokens=max_tokens,  # will be overridden per-sample if 0
        num_workers=num_workers,
    )

    def _call_one(sample: dict) -> str:
        msgs = _build_messages(sample["question"])
        n_constraints = len(_re.findall(r"Step \d+ must precede Step \d+\.", sample["question"]))
        tok = (
            max_tokens
            if max_tokens > 0
            else _estimate_max_tokens(sample["n_steps"], n_constraints)
        )
        original_cfg = llm.config.copy()
        llm.config = {**original_cfg, "max_tokens": tok}
        try:
            return llm.chat(msgs)
        finally:
            llm.config = original_cfg

    def _batch_call(batch_samples: list[tuple[int, dict]]) -> dict[int, str | None]:
        results_map: dict[int, str | None] = {}
        with concurrent.futures.ThreadPoolExecutor(max_workers=num_workers) as ex:
            future_to_idx = {
                ex.submit(_call_one, s): idx for idx, s in batch_samples
            }
            for fut in concurrent.futures.as_completed(future_to_idx):
                idx = future_to_idx[fut]
                try:
                    results_map[idx] = fut.result()
                except Exception:
                    results_map[idx] = None
        return results_map

    # Initial pass
    responses: list[str | None] = [None] * len(samples)
    with concurrent.futures.ThreadPoolExecutor(max_workers=num_workers) as ex:
        future_to_idx = {ex.submit(_call_one, s): i for i, s in enumerate(samples)}
        with tqdm(total=len(samples), desc="Rewriting NL questions", unit="msg") as pbar:
            for fut in concurrent.futures.as_completed(future_to_idx):
                idx = future_to_idx[fut]
                try:
                    responses[idx] = fut.result()
                except Exception as e:
                    pbar.write(f"Error on sample {idx}: {e}")
                    responses[idx] = None
                pbar.update(1)

    # Retry loop for failed validations
    for retry in range(max_retries):
        failed_indices = [
            i for i, (sample, resp) in enumerate(zip(samples, responses))
            if not _validate_rewrite(sample["question"], (resp or "").strip(), sample["n_steps"])
        ]
        if not failed_indices:
            break
        print(f"\nRetry {retry + 1}/{max_retries}: {len(failed_indices)} samples failed validation")
        batch = [(i, samples[i]) for i in failed_indices]
        retry_results = _batch_call(batch)
        for idx, resp in retry_results.items():
            if resp is not None:
                responses[idx] = resp

    results = []
    n_ok = 0
    n_fallback = 0

    for sample, resp in zip(samples, responses):
        new_sample = dict(sample)
        rewrite = (resp or "").strip()

        if _validate_rewrite(
            sample["question"], rewrite, sample["n_steps"]
        ):
            new_sample["question"] = rewrite
            new_sample["question_abstract"] = sample["question"]
            graph = new_sample.get("graph", {})
            if graph.get("step_to_node"):
                durations = parse_node_durations(rewrite, graph)
                if durations is not None:
                    graph["durations"] = durations
                    new_sample["answer"] = compute_gold_makespan(rewrite, graph)
                    real_metrics = compute_metrics({
                        "n_steps":   new_sample["n_steps"],
                        "durations": durations,
                        "edges":     graph["edges"],
                    })
                    new_sample["par_ratio"]    = real_metrics["par_ratio"]
                    new_sample["cp_node_frac"] = real_metrics["cp_node_frac"]
            n_ok += 1
        else:
            new_sample["nl_rewrite_failed"] = True
            n_fallback += 1

        results.append(new_sample)

    print(f"\nRewrite results: {n_ok} succeeded, {n_fallback} fell back to abstract")
    return results


def main():
    parser = argparse.ArgumentParser(
        description="Rewrite synthetic DAG questions into realistic NL via LLM."
    )
    parser.add_argument("--input", required=True, help="Input JSON file from gen_dag.py")
    parser.add_argument("--output", default="", help="Output path (default: auto-named)")
    parser.add_argument("--output-dir", default="", help="Output directory (auto-named file, overrides input dir)")
    parser.add_argument(
        "--model", default="claude-4.5-haiku",
        help="LLM model name [claude-4.5-haiku]"
    )
    parser.add_argument("--temperature", type=float, default=0.8)
    parser.add_argument("--max-tokens", type=int, default=0,
                        help="Max output tokens per sample (0 = auto-scale with n_steps)")
    parser.add_argument("--workers", type=int, default=8,
                        help="Parallel LLM calls [8]")
    parser.add_argument("--limit", type=int, default=0,
                        help="Only process first N samples (0 = all)")
    parser.add_argument("--max-retries", type=int, default=_MAX_REWRITE_RETRIES,
                        help=f"Max retries for failed rewrites [{_MAX_REWRITE_RETRIES}]")
    args = parser.parse_args()

    in_path = Path(args.input)
    if not in_path.exists():
        print(f"Input file not found: {in_path}", file=sys.stderr)
        sys.exit(1)

    samples = json.loads(in_path.read_text(encoding="utf-8"))
    if args.limit > 0:
        samples = samples[: args.limit]

    print(f"Loaded {len(samples)} samples from {in_path}")
    print(f"Model: {args.model}  workers: {args.workers}  temperature: {args.temperature}")

    results = rewrite_dataset(
        samples,
        model_name=args.model,
        temperature=args.temperature,
        max_tokens=args.max_tokens,
        num_workers=args.workers,
        max_retries=args.max_retries,
    )

    # Auto-name output
    if args.output:
        out_path = Path(args.output)
    else:
        safe_model = args.model.replace("/", "-").replace(":", "-")
        auto_name = in_path.stem + f"_nlrewrite_{safe_model}" + in_path.suffix
        out_dir = Path(args.output_dir) if args.output_dir else in_path.parent
        out_path = out_dir / auto_name

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(
        json.dumps(results, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    print(f"\nSaved to {out_path}")


if __name__ == "__main__":
    main()



# USER_TEMPLATE_WITH_DURATIONS = """\
# Below is an abstract planning problem. Rewrite it as a realistic, everyday scenario.

# Rules you MUST follow:
# 1. Keep the EXACT same number of steps.
# 2. Keep EVERY step duration UNCHANGED (copy the times word-for-word).
# 3. Keep ALL ordering constraints UNCHANGED (copy "Step X must precede Step Y" lines word-for-word, same step numbers).
# 4. Change ONLY: the overall task description and each step's activity name.
# 5. Use a single coherent domain (e.g. cooking a dish, renovating a room, setting up a computer, planning a trip, assembling furniture, organising an event…).
# 6. Step names should be concrete actions a real person would perform (not "phase A").
# 7. Output ONLY the rewritten problem text — no commentary, no markdown fences.

# The output must follow this exact format:
# To [task description], here are the steps and the times needed for each step.
# Step 1. [activity name] ([duration])
# Step 2. [activity name] ([duration])
# ...
# These ordering constraints need to be obeyed when executing above steps:
# Step X must precede Step Y.
# ...
# Question: Assume that you need to execute all the steps to complete the task and that infinite resources are available. What is the shortest possible time to [task description]?

# Abstract problem to rewrite:
# {abstract_question}"""