"""
Rewrite abstract synthetic DAG questions into realistic NL scenarios via LLM.

Takes a JSON file generated by gen_dag.py (with generic "Complete phase A/B/C" steps)
and replaces each `question` field with a realistic, domain-specific rewrite produced
by an LLM — while keeping durations, step count, and ordering constraints identical.

Usage
-----
python -m src.gen_data.rewrite_nl \\
    --input  data/synthetic/steps5-9_depth3-5_...json \\
    --model  claude-4.5-haiku \\
    --workers 8

Output is saved to the same directory with `_nlrewrite` appended to the stem,
e.g. steps5-9_depth3-5_..._nlrewrite_claude-4.5-haiku.json

The LLM is instructed to:
  • Invent a realistic everyday task (cooking, home improvement, software setup, …)
  • Give each step a concrete, activity-specific name
  • Preserve EVERY duration and EVERY "Step X must precede Step Y" constraint verbatim
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

from dotenv import load_dotenv
load_dotenv()

from src.experiments.utils import build_llm_client


# ── Prompt ────────────────────────────────────────────────────────────────────

SYSTEM_PROMPT = """\
You are a creative writer who turns abstract planning problems into realistic, \
natural-language scenarios. Your rewrites are used as test questions for AI planning \
systems, so structural accuracy is critical."""

USER_TEMPLATE = """\
Below is an abstract planning problem. Rewrite it as a realistic, everyday scenario.

Rules you MUST follow:
1. Keep the EXACT same number of steps.
2. Keep EVERY step duration UNCHANGED (copy the times word-for-word).
3. Keep ALL ordering constraints UNCHANGED (copy "Step X must precede Step Y" lines \
word-for-word, same step numbers).
4. Change ONLY: the overall task description and each step's activity name.
5. Use a single coherent domain (e.g. cooking a dish, renovating a room, \
setting up a computer, planning a trip, assembling furniture, organising an event…).
6. Step names should be concrete actions a real person would perform (not "phase A").
7. Output ONLY the rewritten problem text — no commentary, no markdown fences.

The output must follow this exact format:
To [task description], here are the steps and the times needed for each step.
Step 1. [activity name]. ([duration])
Step 2. [activity name]. ([duration])
...
These ordering constraints need to be obeyed when executing above steps:
Step X must precede Step Y.
...

Abstract problem to rewrite:
{abstract_question}"""


def _build_messages(abstract_question: str) -> list[dict]:
    return [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": USER_TEMPLATE.format(abstract_question=abstract_question)},
    ]


# ── Validation ────────────────────────────────────────────────────────────────

def _validate_rewrite(original: str, rewrite: str, n_steps: int) -> bool:
    """
    Sanity check: rewrite has the right number of step lines, preserves
    all constraint step-number pairs, and preserves all durations.
    """
    if not rewrite or not rewrite.strip():
        return False

    # Check step count
    step_lines = re.findall(r"^Step \d+\.", rewrite, re.MULTILINE)
    if len(step_lines) != n_steps:
        return False

    # Constraints: check that all (X, Y) pairs appear in rewrite (order-insensitive)
    orig_pairs = set(
        re.findall(r"Step (\d+) must precede Step (\d+)\.", original)
    )
    rewrite_pairs = set(
        re.findall(r"Step (\d+) must precede Step (\d+)\.", rewrite)
    )
    if orig_pairs != rewrite_pairs:
        return False

    # All original durations must appear verbatim
    orig_durations = re.findall(r"\([^)]+\)", original)
    rewrite_text = rewrite
    for d in orig_durations:
        if d not in rewrite_text:
            return False

    return True


def _estimate_max_tokens(n_steps: int, n_constraints: int) -> int:
    """Estimate token budget: ~25 tokens/step + ~15 tokens/constraint + 100 overhead."""
    return max(512, n_steps * 25 + n_constraints * 15 + 200)


# ── Main pipeline ─────────────────────────────────────────────────────────────

def rewrite_dataset(
    samples: list[dict],
    model_name: str,
    temperature: float,
    max_tokens: int,
    num_workers: int,
) -> list[dict]:
    import re as _re
    import concurrent.futures
    from tqdm import tqdm

    llm = build_llm_client(
        model_name=model_name,
        temperature=temperature,
        max_tokens=max_tokens,  # will be overridden per-sample if 0
        num_workers=num_workers,
    )

    def _call_one(sample: dict) -> str:
        msgs = _build_messages(sample["question"])
        n_constraints = len(_re.findall(r"Step \d+ must precede Step \d+\.", sample["question"]))
        tok = (
            max_tokens
            if max_tokens > 0
            else _estimate_max_tokens(sample["n_steps"], n_constraints)
        )
        # Temporarily override max_tokens for this call
        original_cfg = llm.config.copy()
        llm.config = {**original_cfg, "max_tokens": tok}
        try:
            return llm.chat(msgs)
        finally:
            llm.config = original_cfg

    responses = []
    with concurrent.futures.ThreadPoolExecutor(max_workers=num_workers) as ex:
        future_to_idx = {ex.submit(_call_one, s): i for i, s in enumerate(samples)}
        results_buf: list[str | None] = [None] * len(samples)
        with tqdm(total=len(samples), desc="Rewriting NL questions", unit="msg") as pbar:
            for fut in concurrent.futures.as_completed(future_to_idx):
                idx = future_to_idx[fut]
                try:
                    results_buf[idx] = fut.result()
                except Exception as e:
                    pbar.write(f"Error on sample {idx}: {e}")
                    results_buf[idx] = None
                pbar.update(1)
    responses = results_buf

    results = []
    n_ok = 0
    n_fallback = 0

    for sample, resp in zip(samples, responses):
        new_sample = dict(sample)
        rewrite = (resp or "").strip()

        if _validate_rewrite(sample["question"], rewrite, sample["n_steps"]):
            new_sample["question"] = rewrite
            new_sample["question_abstract"] = sample["question"]  # keep original
            n_ok += 1
        else:
            # Keep original question; mark for easy filtering
            new_sample["nl_rewrite_failed"] = True
            n_fallback += 1

        results.append(new_sample)

    print(f"\nRewrite results: {n_ok} succeeded, {n_fallback} fell back to abstract")
    return results


def main():
    parser = argparse.ArgumentParser(
        description="Rewrite synthetic DAG questions into realistic NL via LLM."
    )
    parser.add_argument("--input", required=True, help="Input JSON file from gen_dag.py")
    parser.add_argument("--output", default="", help="Output path (default: auto-named)")
    parser.add_argument("--output-dir", default="", help="Output directory (auto-named file, overrides input dir)")
    parser.add_argument(
        "--model", default="claude-4.5-haiku",
        help="LLM model name [claude-4.5-haiku]"
    )
    parser.add_argument("--temperature", type=float, default=0.8)
    parser.add_argument("--max-tokens", type=int, default=0,
                        help="Max output tokens per sample (0 = auto-scale with n_steps)")
    parser.add_argument("--workers", type=int, default=8,
                        help="Parallel LLM calls [8]")
    parser.add_argument("--limit", type=int, default=0,
                        help="Only process first N samples (0 = all)")
    args = parser.parse_args()

    in_path = Path(args.input)
    if not in_path.exists():
        print(f"Input file not found: {in_path}", file=sys.stderr)
        sys.exit(1)

    samples = json.loads(in_path.read_text(encoding="utf-8"))
    if args.limit > 0:
        samples = samples[: args.limit]

    print(f"Loaded {len(samples)} samples from {in_path}")
    print(f"Model: {args.model}  workers: {args.workers}  temperature: {args.temperature}")

    results = rewrite_dataset(
        samples,
        model_name=args.model,
        temperature=args.temperature,
        max_tokens=args.max_tokens,
        num_workers=args.workers,
    )

    # Auto-name output
    if args.output:
        out_path = Path(args.output)
    else:
        safe_model = args.model.replace("/", "-").replace(":", "-")
        auto_name = in_path.stem + f"_nlrewrite_{safe_model}" + in_path.suffix
        out_dir = Path(args.output_dir) if args.output_dir else in_path.parent
        out_path = out_dir / auto_name

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(
        json.dumps(results, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    print(f"\nSaved to {out_path}")


if __name__ == "__main__":
    main()
