"""
Hyperparameter vs. accuracy analysis for async_planning baselines.

Reads from results/gen-data-modified/ (baselines, formalizer, formalizer_origin).

Usage:
    # Single model, baselines (default)
    python analysis/parameter_performance.py

    # Same model, compare methods (all three)
    python analysis/parameter_performance.py --method baselines formalizer formalizer_origin

    # Same method, compare inference models (data was generated by gemini-3-flash)
    python analysis/parameter_performance.py \
        --model gemini-3-flash openai_gpt-4.1 openai_gpt-5-mini \
        --method baselines \
        --data-model gemini-3-flash

    # Compare both inference models and methods (full grid)
    python analysis/parameter_performance.py \
        --model gemini-3-flash openai_gpt-4.1 openai_gpt-5-mini \
        --method baselines formalizer \
        --data-model gemini-3-flash

    # Save figure to custom path
    python analysis/parameter_performance.py --output analysis/figures/my_fig.png

    # Print table only, no plot
    python analysis/parameter_performance.py --no-plot

    # Custom results directory
    python analysis/parameter_performance.py --results-dir results/gen-data
"""

import argparse
import json
from pathlib import Path

import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import numpy as np
import pandas as pd

ROOT = Path(__file__).parent.parent
DATA_DIR = ROOT / "data" / "async_planning"
RESULTS_DIR = ROOT / "results" / "gen-data-modified"

NODE_SIZES = [5, 10, 15, 20, 30, 40, 50, 100]

# Color cycles per model (up to 6 models supported)
MODEL_PALETTE = ["#e05252", "#2a9d8f", "#e8a838", "#5b8dd9", "#9b59b6", "#555555"]

# Visual encoding per method (marker + linestyle; color comes from model)
METHOD_VISUAL = {
    "baselines":        {"marker": "o", "ls": "-",  "label": "Planner"},
    "formalizer":       {"marker": "s", "ls": "--", "label": "Formalizer (PDDL)"},
    "formalizer_origin": {"marker": "s", "ls": ":",  "label": "Formalizer (origin)"},
}


def _series_label(model: str, method: str, all_models: list[str], all_methods: list[str]) -> str:
    """Human-readable legend label for a (model, method) series."""
    multi_model = len(all_models) > 1
    multi_method = len(all_methods) > 1
    method_label = METHOD_VISUAL.get(method, {}).get("label", method)
    if multi_model and multi_method:
        return f"{model} / {method_label}"
    if multi_model:
        return model
    if multi_method:
        return method_label
    return f"{model} — {method_label}"


def _series_style(
    model: str, method: str, all_models: list[str]
) -> dict:
    model_idx = all_models.index(model) if model in all_models else 0
    visual = METHOD_VISUAL.get(method, {"marker": "o", "ls": "-", "label": method})
    return {
        "color": MODEL_PALETTE[model_idx % len(MODEL_PALETTE)],
        "marker": visual["marker"],
        "ls": visual["ls"],
    }


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------


def _parse_concatenated_json(text: str) -> list[dict]:
    """Parse a file that contains multiple JSON objects concatenated (not JSONL)."""
    decoder = json.JSONDecoder()
    objects = []
    idx = 0
    text = text.strip()
    while idx < len(text):
        while idx < len(text) and text[idx].isspace():
            idx += 1
        if idx >= len(text):
            break
        obj, end_idx = decoder.raw_decode(text, idx)
        objects.append(obj)
        idx = end_idx
    return objects


def _results_path(inf_model: str, method: str, n: int, data_model: str) -> Path:
    """
    inf_model  – inference model = folder name under baselines/ or formalizer/
                 e.g. "gemini-3-flash", "openai_gpt-4.1"
    data_model – data-generation model = suffix in the dataset tag
                 e.g. "gemini-3-flash"
    """
    tag = f"nodes{n}_n50_s42_nlrewrite_{data_model}"
    if method == "baselines":
        return RESULTS_DIR / "baselines" / inf_model / tag / "cot" / "full_results.jsonl"
    if method == "formalizer_origin":
        return RESULTS_DIR / "formalizer_origin" / inf_model / tag / "full_results.jsonl"
    return RESULTS_DIR / "formalizer" / inf_model / tag / "full_results.jsonl"


def load_method_df(inf_model: str, method: str, data_model: str) -> pd.DataFrame:
    """Join data-file hyperparameters with result correctness labels.

    inf_model  – inference model (results folder name)
    data_model – data-generation model (dataset filename suffix)
    """
    records = []
    for n in NODE_SIZES:
        data_file = DATA_DIR / f"nodes{n}_n50_s42_nlrewrite_{data_model}.json"
        results_file = _results_path(inf_model, method, n, data_model)
        if not data_file.exists() or not results_file.exists():
            continue
        with open(data_file) as f:
            data_items = json.load(f)
        result_items = _parse_concatenated_json(results_file.read_text())
        for d, r in zip(data_items, result_items):
            records.append(
                {
                    "n_steps": int(d["n_steps"]),
                    "par_ratio": float(d["par_ratio"]),
                    "path_count": int(d["path_count"]),
                    "edge_density": float(d["edge_density"]),
                    "critical_path_length": int(d["critical_path_length"]),
                    "correct": int(r["correct"]),
                }
            )
    return pd.DataFrame(records)


# ---------------------------------------------------------------------------
# Statistics helpers
# ---------------------------------------------------------------------------


def _wilson_ci(p: float, n: int, z: float = 1.96) -> tuple[float, float]:
    """Wilson score 95% confidence interval for a proportion."""
    if n == 0 or np.isnan(p):
        return (np.nan, np.nan)
    denom = 1 + z**2 / n
    center = (p + z**2 / (2 * n)) / denom
    margin = z * np.sqrt(p * (1 - p) / n + z**2 / (4 * n**2)) / denom
    return (center - margin, center + margin)


def _binned_accuracy(
    x: pd.Series, y: pd.Series, n_bins: int = 8, log_scale: bool = False
) -> pd.DataFrame:
    """Return DataFrame with columns: x_mid, acc, ci_lo, ci_hi, n."""
    if log_scale:
        lo, hi = np.log10(x.clip(lower=1).min()), np.log10(x.clip(lower=1).max())
        edges = np.logspace(lo, hi, n_bins + 1)
        labels = [
            f"{edges[i]:.0f}–{edges[i+1]:.0f}" for i in range(n_bins)
        ]
        bins = pd.cut(x, bins=edges, labels=labels, include_lowest=True)
        x_mids = (edges[:-1] + edges[1:]) / 2
    else:
        try:
            bins = pd.qcut(x, q=n_bins, duplicates="drop")
        except ValueError:
            bins = pd.cut(x, bins=n_bins)
        x_mids = None  # will compute from group mean

    df = pd.DataFrame({"x": x, "y": y, "bin": bins})
    rows = []
    for bin_label, grp in df.groupby("bin", observed=True):
        n = len(grp)
        acc = grp["y"].mean()
        lo, hi = _wilson_ci(acc, n)
        x_mid = grp["x"].mean() if x_mids is None else x_mids[list(df["bin"].cat.categories).index(bin_label)]
        rows.append({"x_mid": x_mid, "acc": acc, "ci_lo": lo, "ci_hi": hi, "n": n})
    return pd.DataFrame(rows).dropna(subset=["acc"])


def _discrete_accuracy(x: pd.Series, y: pd.Series) -> pd.DataFrame:
    """Accuracy per unique x value (for n_steps)."""
    rows = []
    for val in sorted(x.unique()):
        grp = y[x == val]
        n = len(grp)
        acc = grp.mean()
        lo, hi = _wilson_ci(acc, n)
        rows.append({"x_mid": val, "acc": acc, "ci_lo": lo, "ci_hi": hi, "n": n})
    return pd.DataFrame(rows)


# ---------------------------------------------------------------------------
# Plotting
# ---------------------------------------------------------------------------

PANEL_CFG = [
    {
        "col": "n_steps",
        "title": "# Tasks (Steps)",
        "xlabel": "Number of tasks  [log₂ scale]",
        "discrete": True,
        "log_x": True,
        "n_bins": None,
        "note": "Measures absolute problem size",
    },
    {
        "col": "par_ratio",
        "title": "Parallelism Ratio",
        "xlabel": "par_ratio  =  n_steps / critical_path_length",
        "discrete": False,
        "log_x": False,
        "n_bins": 8,
        "note": "Higher → more parallelism available",
    },
    {
        "col": "path_count",
        "title": "Path Count",
        "xlabel": "Number of distinct DAG paths  [log₁₀ scale]",
        "discrete": False,
        "log_x": True,
        "n_bins": 8,
        "note": "Higher → more complex dependency graph",
    },
    {
        "col": "edge_density",
        "title": "Edge Density",
        "xlabel": "edge_density  =  edges / max_possible_edges",
        "discrete": False,
        "log_x": False,
        "n_bins": 8,
        "note": "Higher → denser dependency graph",
    },
]


def plot_hyperparameter_analysis(
    dfs: dict[str, pd.DataFrame],
    output_path: Path | None = None,
    all_models: list[str] | None = None,
    all_methods: list[str] | None = None,
) -> None:
    all_models = all_models or []
    all_methods = all_methods or []
    fig, axes = plt.subplots(2, 2, figsize=(14, 9))
    axes = axes.flatten()

    for ax, cfg in zip(axes, PANEL_CFG):
        col = cfg["col"]
        for key, df in dfs.items():
            if df.empty or col not in df.columns:
                continue
            model, method = key.split("/", 1)
            style = _series_style(model, method, all_models)
            color = style["color"]
            marker = style["marker"]
            ls = style["ls"]
            label = _series_label(model, method, all_models, all_methods)

            if cfg["discrete"]:
                stats_df = _discrete_accuracy(df[col], df["correct"])
            else:
                stats_df = _binned_accuracy(
                    df[col], df["correct"], n_bins=cfg["n_bins"], log_scale=cfg["log_x"]
                )

            xs = stats_df["x_mid"].values
            ys = stats_df["acc"].values
            lo = stats_df["ci_lo"].values
            hi = stats_df["ci_hi"].values
            ns = stats_df["n"].values

            ax.plot(xs, ys, marker=marker, ls=ls, color=color, label=label, lw=2, ms=7, zorder=3)
            ax.fill_between(xs, lo, hi, alpha=0.18, color=color, zorder=2)

            # Annotate sample count per bin
            for xi, yi, ni in zip(xs, ys, ns):
                ax.annotate(
                    f"n={int(ni)}",
                    xy=(xi, yi),
                    xytext=(0, 9),
                    textcoords="offset points",
                    ha="center",
                    fontsize=6.5,
                    color=color,
                    alpha=0.75,
                )

        ax.set_title(cfg["title"], fontsize=12, fontweight="bold")
        ax.set_xlabel(cfg["xlabel"], fontsize=9.5)
        ax.set_ylabel("Accuracy", fontsize=10)
        ax.set_ylim(-0.05, 1.12)
        ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda y, _: f"{y:.0%}"))
        ax.axhline(0.5, color="gray", ls=":", alpha=0.5, lw=1.2, label="50% chance")
        ax.grid(True, alpha=0.3, linewidth=0.7)
        ax.legend(fontsize=8.5, loc="upper right")

        if cfg["log_x"]:
            ax.set_xscale("log")
            if cfg["discrete"]:
                all_sizes = sorted(set().union(*[df["n_steps"].unique() for df in dfs.values() if not df.empty]))
                ax.set_xticks(all_sizes)
                ax.set_xticklabels([str(s) for s in all_sizes], fontsize=8)
                ax.xaxis.set_minor_formatter(mticker.NullFormatter())

        # Note in bottom-left corner
        ax.text(
            0.02, 0.04, cfg["note"],
            transform=ax.transAxes, fontsize=7.5, color="gray",
            va="bottom", ha="left", style="italic"
        )

    model_str = " / ".join(all_models) if all_models else ""
    methods_str = " vs ".join(
        METHOD_VISUAL.get(m, {}).get("label", m) for m in all_methods
    ) if all_methods else ""
    subtitle = "  ·  ".join(filter(None, [model_str, methods_str]))
    fig.suptitle(
        f"Accuracy vs. Problem Hyperparameters\n{subtitle}",
        fontsize=13,
        fontweight="bold",
        y=1.01,
    )
    plt.tight_layout()

    if output_path:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        plt.savefig(output_path, dpi=150, bbox_inches="tight")
        print(f"Saved figure → {output_path}")
    else:
        plt.show()
    plt.close()


# ---------------------------------------------------------------------------
# Summary table
# ---------------------------------------------------------------------------


def print_summary_table(
    dfs: dict[str, pd.DataFrame],
    all_models: list[str],
    all_methods: list[str],
) -> None:
    keys = list(dfs.keys())
    all_sizes = sorted(
        set().union(*[set(df["n_steps"].tolist()) for df in dfs.values() if not df.empty])
    )
    col_w = 18

    def _key_label(key: str) -> str:
        model, method = key.split("/", 1)
        return _series_label(model, method, all_models, all_methods)

    print("\n" + "=" * (10 + col_w * len(keys)))
    print("Accuracy by Number of Steps")
    print("=" * (10 + col_w * len(keys)))

    header = f"{'n_steps':>8}"
    for k in keys:
        header += f"  {_key_label(k):>{col_w - 2}}"
    print(header)
    print("-" * (10 + col_w * len(keys)))

    for n in all_sizes:
        row = f"{n:>8}"
        for k in keys:
            df = dfs[k]
            if df.empty or n not in df["n_steps"].values:
                row += f"  {'—':>{col_w - 2}}"
            else:
                sub = df[df["n_steps"] == n]
                acc = sub["correct"].mean()
                total = len(sub)
                correct = sub["correct"].sum()
                row += f"  {acc:.3f}  ({correct:>2}/{total})"
        print(row)

    print("=" * (10 + col_w * len(keys)))

    # Correlation table
    print("\n" + "=" * 60)
    print("Point-biserial correlation with accuracy  (all sizes pooled)")
    print("=" * 60)
    params = ["n_steps", "par_ratio", "path_count", "edge_density"]
    header = f"{'param':>20}"
    for k in keys:
        header += f"  {_key_label(k):>18}"
    print(header)
    print("-" * 60)
    for p in params:
        row = f"{p:>20}"
        for k in keys:
            df = dfs[k]
            if df.empty or p not in df.columns:
                row += f"  {'—':>18}"
                continue
            r = df[p].corr(df["correct"])
            row += f"  {r:>+.3f}{'':>12}"
        print(row)
    print("=" * 60)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Plot accuracy vs. hyperparameters for async_planning benchmarks"
    )
    parser.add_argument(
        "--model",
        nargs="+",
        default=["gemini-3-flash"],
        choices=["gemini-3-flash", "openai_gpt-5-mini", "openai_gpt-4.1"],
        help="Model name(s) to compare",
    )
    parser.add_argument(
        "--method",
        nargs="+",
        default=["baselines"],
        choices=["baselines", "formalizer_origin", "formalizer"],
        help="Method(s) to compare",
    )
    parser.add_argument(
        "--data-model",
        default="gemini-3-flash",
        dest="data_model",
        help="Data-generation model used in dataset filenames (default: gemini-3-flash)",
    )
    parser.add_argument(
        "--output",
        default=None,
        help="Output figure path (default: analysis/figures/hyperparam_<models>_<methods>.png)",
    )
    parser.add_argument(
        "--no-plot", action="store_true", help="Skip plotting; only print table"
    )
    parser.add_argument(
        "--results-dir",
        default=None,
        help="Override results directory (default: results/gen-data-modified)",
    )
    args = parser.parse_args()

    if args.results_dir:
        global RESULTS_DIR
        RESULTS_DIR = ROOT / args.results_dir

    all_models: list[str] = args.model
    all_methods: list[str] = args.method
    data_model: str = args.data_model

    dfs: dict[str, pd.DataFrame] = {}
    for model in all_models:
        for method in all_methods:
            key = f"{model}/{method}"
            print(f"Loading {method} data for {model} (data-model={data_model}) …")
            df = load_method_df(model, method, data_model)
            if df.empty:
                print(f"  [!] No data found for model={model}, method={method}")
            else:
                print(
                    f"  Loaded {len(df)} examples across "
                    f"{df['n_steps'].nunique()} node sizes: {sorted(df['n_steps'].unique())}"
                )
            dfs[key] = df

    print_summary_table(dfs, all_models, all_methods)

    if not args.no_plot:
        if args.output:
            output_path = ROOT / args.output
        else:
            models_tag = "_".join(all_models)
            methods_tag = "_".join(all_methods)
            output_path = (
                ROOT / "analysis" / "figures" / f"hyperparam_{models_tag}_{methods_tag}.png"
            )
        plot_hyperparameter_analysis(
            dfs,
            output_path=output_path,
            all_models=all_models,
            all_methods=all_methods,
        )


if __name__ == "__main__":
    main()
